[pytest]
; [pytest] обязательно должно быть в .ini

pythonpath = .

asyncio_mode = auto

  ; все тесты асинхронные автоматически

testpaths = tests
  ; поиск тестов только в папке /tests

markers =
    database: tests for database layer
    services: tests for service layer
    controllers: tests for API layer

; какие еще параметры существуют
; addopts = -v -ra --disable-warnings  # дополнительные параметры по умолчанию. Всё, что здесь указано, pytest будет применять при каждом запуске.
; filterwarnings =
;     ignore::DeprecationWarning
;     ignore::UserWarning